### ISSUE TITLE
Change the default location for modules

### ISSUE THREAD

**Issue by antonbabenko** [devopsmakers/xterrafile#4]
Thanks for this great addition to the Terraform ecosystem!

I have a few questions/proposals:

1. Let's change default location from `vendor/xterrafile` to `vendor/modules`.
1. Do you have plans to continue working on this? If so, here are features I'd like to have:

- Add support for conditions in `version` (eg, `version: "~> 2.0"`)
- Add `update` / `lock` commands

**Comment by pysysops** [comment]
Hi @antonbabenko I hope you're well. Thanks for the positive feedback and suggestions. 

I do have plans to extend `xterrafile`. I'm planning on refactoring the go-getter code a bit and adding support for conditional versioning quite soon. 

Originally, I had thought about a generic default directory name but thought it might clash with something else that vendored modules. That said, I'm not against changing it.

Update and lock functionality may be a little trickier to get right. What do you envision the user experience of those commands to be? Any examples of tools that do a good job of it?

Originally, I created this as a tool to live in the root of an infra / terraform repo. Since, I've realised it's probably useful for stack or service modules... Those modules that often make use of multiple upstream modules to create a fully formed "thing".

**Comment by antonbabenko** [comment]
## conditions

I would like to have a way to specify condition like this:
```
terraform-digitalocean-droplet:
  source: "terraform-digitalocean-modules/droplet/digitalocean"
  version: "~> 2.0"
```

And then run `xterrafile install` and get latest module installed in vendor which match `~> 2.0` rule.

## update/lock

One of the examples of the tool which does similar - [composer update](https://getcomposer.org/doc/03-cli.md#update-u). Similar features are also provided by other package management systems like npm, pip, gem.

**Comment by daks** [comment]
It reminds me how Ruby bundle (which uses Gemfile/Gemfile.lock) works. A library named `librarian` implements this behaviour which is also used to manage Puppet, Chef, Ansible dependencies _(search for librarian-* tools)_. _(like xterrafile is also used by some to manage Salt dependencies)_

**Comment by pysysops** [comment]
Thanks @antonbabenko / @daks,

I understand how lock files work with other package managers out there (especially librarian). I've even written tooling to reverse engineer .lock files for things like librarian-puppet to r10k migrations (https://gist.github.com/timbirk/0308d8128927ec0f66011d7726980a9e). 

I'm just trying to understand the benefit to adding this functionality to `xterrafile` and how that might fit into some sort of practice when it comes to authoring and making use of Terrafile's / Terraform modules.

I think conditional versioning is a good place to start whilst refactoring the code as the `install` command is a bit more monolithic than I'd like it to be and parts of that code will be required in the `update` command in the future. I'll have a look at that sometime over the next week.

**Comment by pysysops** [comment]
Closing in favour of #5, #6, #7 and #8

**Comment by pysysops** [comment]
@antonbabenko I've implemented https://github.com/blang/semver to introduce conditional versioning. This is only for registry modules at the moment. I'd definitely like to implement it for git tags 🔜- you can find instructions on ranges in the README.

The new default download directory is: `vendor/modules`

As always, any feedback or 🐛reports are always welcome.
